Repository zeta-chain/localnet, pull requests merged in 2025-04, with the labels that each got.

#148 feat: add TON to localnet
  .eslintrc.js
  package.json
  packages/commands/src/index.ts
  packages/commands/src/start.ts
  packages/commands/src/ton.ts
  packages/localnet/src/chains/ton/config.ts
  packages/localnet/src/chains/ton/deployer.ts
  packages/localnet/src/chains/ton/gateway.ts
  packages/localnet/src/chains/ton/index.ts
  packages/localnet/src/chains/ton/node.ts
  packages/localnet/src/chains/ton/setup.ts
  packages/localnet/src/constants.ts
  packages/localnet/src/docker/docker.ts
  packages/localnet/src/docker/index.ts
  packages/localnet/src/index.ts
  packages/localnet/src/log.ts
  packages/localnet/src/utils/index.ts
  packages/localnet/src/utils/requests.ts
  packages/localnet/src/utils/retry.ts
  packages/localnet/src/utils/ton.ts
  packages/localnet/src/zetachainDepositAndCall.ts
  packages/localnet/src/zetachainWithdraw.ts
  packages/tasks/src/localnet.ts
  yarn.lock
Labels: enhancement

#153 chore: rename `changelog.yml` to `release.yml`
  .github/release.yml
Labels: chore

#156 fix(ton): drop misleading log
  packages/localnet/src/chains/ton/gateway.ts
Labels: fix

#160 fix: move readline inside the start command
  packages/commands/src/start.ts
Labels: fix
