Repository zeta-chain/localnet, pull requests merged in 2025-05, with the labels that each got.

#162 feat!: update localnet to use bytes sender in context
  package.json
  packages/localnet/src/zetachainDepositAndCall.ts
  packages/localnet/src/zetachainExecute.ts
  yarn.lock
Labels: feat, breaking change

#159 chore: rename Sui Gateway module to package
  packages/localnet/src/suiDeposit.ts
  packages/localnet/src/suiDepositAndCall.ts
  packages/localnet/src/suiSetup.ts
  packages/localnet/src/suiWithdraw.ts
  packages/localnet/src/suiWithdrawAndCall.ts
  packages/localnet/src/tokens/createSuiToken.ts
  packages/tasks/src/suiDeposit.ts
  packages/tasks/src/suiDepositAndCall.ts
  packages/tasks/src/utils/sui.ts
Labels: chore

#161 fix: make localnet run correctly in background
  packages/commands/src/start.ts
Labels: fix

#164 ci: Update release-to-discord.yml
  .github/workflows/release-to-discord.yml
Labels: ci

#166 feat: `start --verbosity <level>` flag
  package.json
  packages/commands/src/start.ts
  packages/localnet/src/chains/ton/gateway.ts
  packages/localnet/src/chains/ton/node.ts
  packages/localnet/src/chains/ton/setup.ts
  packages/localnet/src/cloneRepository.ts
  packages/localnet/src/constants.ts
  packages/localnet/src/evmCall.ts
  packages/localnet/src/evmCustodyWithdraw.ts
  packages/localnet/src/evmDeposit.ts
  packages/localnet/src/evmDepositAndCall.ts
  packages/localnet/src/evmExecute.ts
  packages/localnet/src/evmOnRevert.ts
  packages/localnet/src/evmTSSTransfer.ts
  packages/localnet/src/log.ts
  packages/localnet/src/logger.ts
  packages/localnet/src/solanaDeposit.ts
  packages/localnet/src/solanaDepositAndCall.ts
  packages/localnet/src/solanaExecute.ts
  packages/localnet/src/solanaSetup.ts
  packages/localnet/src/solanaWithdraw.ts
  packages/localnet/src/solanaWithdrawSPL.ts
  packages/localnet/src/suiDeposit.ts
  packages/localnet/src/suiDepositAndCall.ts
  packages/localnet/src/suiSetup.ts
  packages/localnet/src/suiWithdraw.ts
  packages/localnet/src/suiWithdrawAndCall.ts
  packages/localnet/src/tokens/createSolanaToken.ts
  packages/localnet/src/tokens/createSuiToken.ts
  packages/localnet/src/tokens/uniswapV3.ts
  packages/localnet/src/zetachainCall.ts
  packages/localnet/src/zetachainDeposit.ts
  packages/localnet/src/zetachainDepositAndCall.ts
  packages/localnet/src/zetachainExecute.ts
  packages/localnet/src/zetachainOnAbort.ts
  packages/localnet/src/zetachainOnRevert.ts
  packages/localnet/src/zetachainSwapToCoverGas.ts
  packages/localnet/src/zetachainWithdraw.ts
  packages/localnet/src/zetachainWithdrawAndCall.ts
  yarn.lock
Labels: feat

#170 feat!: replace `--skip` with `--chains` to explicitly enable chains
  packages/commands/src/start.ts
  packages/localnet/src/index.ts
  packages/tasks/src/localnet.ts
Labels: feat, breaking change

#174 fix: set non-EVM sender address correctly
  src/chains/sui/depositAndCall.ts
  src/chains/zetachain/depositAndCall.ts
  src/logger.ts
Labels: fix

#175 fix: do not stop TON if it has not been enabled
  src/commands/start.ts
Labels: fix

#177 chore: Use logger for tables
  src/commands/start.ts
  src/logger.ts
Labels: chore

#178 chore: remove readline
  src/commands/start.ts
Labels: chore

#180 chore: add extensive init debug logging
  src/commands/start.ts
  src/index.ts
Labels: chore

#181 fix: await final promise all in create token fn
  src/tokens/createToken.ts
Labels: fix

#182 refactor: remove uniswap v3
  src/chains/zetachain/setup.ts
  src/tokens/createToken.ts
Labels: refactor

#186 fix: remove all dependency cycles
  .eslintrc.js
  src/backgroundProcesses.ts
  src/chains/solana/constants.ts
  src/chains/solana/execute.ts
  src/chains/solana/setup.ts
  src/chains/solana/withdraw.ts
  src/chains/solana/withdrawSPL.ts
  src/chains/sui/suiSetup.ts
  src/commands/start.ts
  src/logger.ts
  src/tokens/createSolanaToken.ts
Labels: fix
